kind: Service
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "260"
  name: redis-standalone-service
  namespace: supercloud
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: redis-standalone