---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "210"
  name: certified-operators
  namespace: openshift-marketplace
spec:
  displayName: Certified Operators
  publisher: Red Hat
  sourceType: grpc
  image: 'registry.redhat.io/redhat/certified-operator-index:v4.10'
  updateStrategy:
    registryPoll:
      interval: 10m0s