apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: redis-enterprise-operator.v6.2.18-41c
  namespace: supercloud
  annotations:
    argocd.argoproj.io/sync-wave: "225"
spec:
  relatedImages:
    - image: >-
        registry.connect.redhat.com/redislabs/redis-enterprise-operator@sha256:0973c8ae3f6d9115c675c32fa63c6404d6afed7c8904d78a184ea3b4e8c4ace8
      name: redis-enterprise-operator
    - image: >-
        registry.connect.redhat.com/redislabs/redis-enterprise-operator@sha256:0973c8ae3f6d9115c675c32fa63c6404d6afed7c8904d78a184ea3b4e8c4ace8
      name: admission-image
    - image: >-
        registry.connect.redhat.com/redislabs/redis-enterprise-operator@sha256:0973c8ae3f6d9115c675c32fa63c6404d6afed7c8904d78a184ea3b4e8c4ace8
      name: bootstrapper-image
    - image: >-
        registry.connect.redhat.com/redislabs/services-manager@sha256:61fcc4e240be3da3908d16e59e2bb96f1334c79d8446d167f6ab39ff550fbb1f
      name: k8s-controller-image
    - image: >-
        registry.connect.redhat.com/redislabs/redis-enterprise@sha256:59ed3c0d804691934d3fde50ae67b9382b8c46cf6f118069adca3796b788bd1f
      name: rs-image
    - image: >-
        registry.connect.redhat.com/redislabs/redis-enterprise-operator@sha256:0973c8ae3f6d9115c675c32fa63c6404d6afed7c8904d78a184ea3b4e8c4ace8
      name: >-
        redis-enterprise-operator-0973c8ae3f6d9115c675c32fa63c6404d6afed7c8904d78a184ea3b4e8c4ace8-annotation
    - image: >-
        registry.connect.redhat.com/redislabs/redis-enterprise-operator@sha256:0973c8ae3f6d9115c675c32fa63c6404d6afed7c8904d78a184ea3b4e8c4ace8
      name: admission
  cleanup:
    enabled: false
  apiservicedefinitions: {}
  webhookdefinitions:
    - generateName: redb.admission.redislabs
      containerPort: 8443
      sideEffects: None
      deploymentName: redis-enterprise-operator
      rules:
        - apiGroups:
            - app.redislabs.com
          apiVersions:
            - v1alpha1
          operations:
            - '*'
          resources:
            - redisenterprisedatabases
      type: ValidatingAdmissionWebhook
      admissionReviewVersions:
        - v1beta1
      webhookPath: /admission
      failurePolicy: Fail
  keywords:
    - redislabs
    - redis
    - database
    - nosql
    - cache
  displayName: Redis Enterprise Operator
  provider:
    name: Redis
  maturity: mature
  skips:
    - redis-enterprise-operator.v5.4.14-7
    - redis-enterprise-operator.v6.0.6-6
    - redis-enterprise-operator.v6.0.6-11
    - redis-enterprise-operator.v6.0.6-23
    - redis-enterprise-operator.v6.0.6-24
    - redis-enterprise-operator.v6.0.8-1
    - redis-enterprise-operator.v6.0.8-20
    - redis-enterprise-operator.v6.0.12-5
    - redis-enterprise-operator.v6.0.20-4
    - redis-enterprise-operator.v6.0.20-12
    - redis-enterprise-operator.v6.0.20-12a
    - redis-enterprise-operator.v6.2.4-1
    - redis-enterprise-operator.v6.2.8-2
    - redis-enterprise-operator.v6.2.8-11
    - redis-enterprise-operator.v6.2.8-15
    - redis-enterprise-operator.v6.2.10-4
    - redis-enterprise-operator.v6.2.10-34
    - redis-enterprise-operator.v6.2.10-45
    - redis-enterprise-operator.v6.2.12-1
    - redis-enterprise-operator.v6.2.18-3
    - redis-enterprise-operator.v6.2.18-3a
    - redis-enterprise-operator.v6.2.18-41a
    - redis-enterprise-operator.v6.2.18-41b
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  version: 6.2.18-41c
  install:
    spec:
      deployments:
        - name: redis-enterprise-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: redis-enterprise-operator
            strategy: {}
            template:
              metadata:
                creationTimestamp: null
                labels:
                  app: redis-enterprise
                  name: redis-enterprise-operator
              spec:
                containers:
                  - resources:
                      limits:
                        cpu: '4'
                        memory: 512Mi
                      requests:
                        cpu: 500m
                        memory: 256Mi
                    name: redis-enterprise-operator
                    command:
                      - redis-enterprise-operator
                    livenessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /healthz
                        port: 8080
                        scheme: HTTP
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 5
                    env:
                      - name: POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: redis-enterprise-operator
                      - name: DEPLOY_RHEL
                        value: 'true'
                      - name: DEFAULT_K8S_CONTROLLER_IMAGE_DIGEST
                        value: >-
                          sha256:61fcc4e240be3da3908d16e59e2bb96f1334c79d8446d167f6ab39ff550fbb1f
                      - name: DEFAULT_BOOTSTRAPPER_IMAGE_DIGEST
                        value: >-
                          sha256:0973c8ae3f6d9115c675c32fa63c6404d6afed7c8904d78a184ea3b4e8c4ace8
                      - name: DEFAULT_RS_IMAGE_DIGEST
                        value: >-
                          sha256:59ed3c0d804691934d3fde50ae67b9382b8c46cf6f118069adca3796b788bd1f
                      - name: BUNDLED_RS_VERSION_OVERRIDE
                        value: 6.2.18-72
                    securityContext:
                      runAsUser: 1001
                    ports:
                      - containerPort: 8080
                        protocol: TCP
                    imagePullPolicy: Always
                    envFrom:
                      - configMapRef:
                          name: operator-environment-config
                          optional: true
                    image: >-
                      registry.connect.redhat.com/redislabs/redis-enterprise-operator@sha256:0973c8ae3f6d9115c675c32fa63c6404d6afed7c8904d78a184ea3b4e8c4ace8
                  - resources:
                      limits:
                        cpu: '1'
                        memory: 512Mi
                      requests:
                        cpu: 250m
                        memory: 256Mi
                    readinessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /healthz
                        port: 8443
                        scheme: HTTPS
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 5
                    name: admission
                    command:
                      - /usr/local/bin/admission
                    livenessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /liveness
                        port: 8443
                        scheme: HTTPS
                      initialDelaySeconds: 15
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 5
                    env:
                      - name: POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: ADMISSION_SERVICE_NAME
                        value: redis-enterprise-operator-service
                      - name: IS_OLM
                        value: 'true'
                    ports:
                      - containerPort: 8443
                        protocol: TCP
                    imagePullPolicy: Always
                    envFrom:
                      - configMapRef:
                          name: operator-environment-config
                          optional: true
                    image: >-
                      registry.connect.redhat.com/redislabs/redis-enterprise-operator@sha256:0973c8ae3f6d9115c675c32fa63c6404d6afed7c8904d78a184ea3b4e8c4ace8
                serviceAccountName: redis-enterprise-operator
      permissions:
        - rules:
            - apiGroups:
                - rbac.authorization.k8s.io
                - ''
              resources:
                - roles
                - serviceaccounts
                - rolebindings
              verbs:
                - bind
                - escalate
                - impersonate
                - userextras
                - create
                - get
                - list
                - watch
                - update
                - patch
                - delete
                - deletecollection
            - apiGroups:
                - app.redislabs.com
              resources:
                - redisenterpriseclusters
                - redisenterpriseclusters/status
                - redisenterpriseclusters/finalizers
                - redisenterprisedatabases
                - redisenterprisedatabases/status
                - redisenterprisedatabases/finalizers
                - redisenterpriseremoteclusters
                - redisenterpriseremoteclusters/status
                - redisenterpriseremoteclusters/finalizers
                - redisenterpriseactiveactivepeerings
                - redisenterpriseactiveactivepeerings/status
                - redisenterpriseactiveactivepeerings/finalizers
              verbs:
                - delete
                - deletecollection
                - get
                - list
                - patch
                - create
                - update
                - watch
            - apiGroups:
                - ''
              resources:
                - secrets
              verbs:
                - update
                - get
                - read
                - list
                - listallnamespaces
                - watch
                - watchlist
                - watchlistallnamespaces
                - create
                - patch
                - replace
                - delete
                - deletecollection
            - apiGroups:
                - ''
              resources:
                - endpoints
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - ''
              resources:
                - events
              verbs:
                - create
                - patch
            - apiGroups:
                - apps
              resources:
                - deployments
                - statefulsets
                - replicasets
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - create
                - delete
                - get
                - list
                - watch
            - apiGroups:
                - ''
              resources:
                - configmaps
              verbs:
                - create
                - delete
                - get
                - update
                - list
                - watch
            - apiGroups:
                - ''
              resources:
                - persistentvolumeclaims
              verbs:
                - create
                - delete
                - get
                - update
                - list
                - watch
            - apiGroups:
                - ''
              resources:
                - pods
              verbs:
                - get
                - watch
                - list
                - update
                - patch
                - delete
            - apiGroups:
                - ''
              resources:
                - services
              verbs:
                - get
                - watch
                - list
                - update
                - patch
                - create
                - delete
            - apiGroups:
                - policy
              resourceNames:
                - redis-enterprise-psp
              resources:
                - podsecuritypolicies
              verbs:
                - use
            - apiGroups:
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - create
                - patch
                - replace
                - delete
                - deletecollection
                - read
                - list
                - listallnamespaces
                - watch
                - watchlist
                - watchlistallnamespaces
                - patchstatus
                - readstatus
                - replacestatus
                - update
            - apiGroups:
                - networking.istio.io
              resources:
                - gateways
                - virtualservices
              verbs:
                - get
                - watch
                - list
                - update
                - patch
                - create
                - delete
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
                - routes/custom-host
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - security.openshift.io
              resourceNames:
                - redis-enterprise-scc
              resources:
                - securitycontextconstraints
              verbs:
                - use
          serviceAccountName: redis-enterprise-operator
        - rules:
            - apiGroups:
                - security.openshift.io
              resourceNames:
                - redis-enterprise-scc
              resources:
                - securitycontextconstraints
              verbs:
                - use
          serviceAccountName: rec
    strategy: deployment