apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "240"
    olm.operatorGroup: supercloud-og
  labels:
    operators.coreos.com/redis-enterprise-operator-cert.supercloud: ''
  name: redis-enterprise-operator-cert
  namespace: supercloud
spec:
  channel: production
  installPlanApproval: Automatic
  name: redis-enterprise-operator-cert
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: redis-enterprise-operator.v6.2.18-41c