kind: RedisEnterpriseCluster
apiVersion: app.redislabs.com/v1
metadata:
  name: rec
  namespace: supercloud
  annotations:
    argocd.argoproj.io/sync-wave: "250"
spec:
  servicesRiggerSpec:
    databaseServiceType: load_balancer
    serviceNaming: redis-port
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: ocs-storagecluster-cephfs
  uiServiceType: ClusterIP
  username: demo@redislabs.com
  # ALLOW_EMPTY_PASSWORD: true
  redisEnterpriseNodeResources:
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
  bootstrapperImageSpec:
    repository: registry.connect.redhat.com/redislabs/redis-enterprise-operator
  redisEnterpriseServicesRiggerImageSpec:
    repository: registry.connect.redhat.com/redislabs/services-manager
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
    repository: registry.connect.redhat.com/redislabs/redis-enterprise