apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "120"
  name: redis-enterprise-operator-sub
  namespace: supercloud
spec:
  channel: production
  installPlanApproval: Automatic
  name: redis-enterprise-operator-sub
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: redis-enterprise-operator.v6.2.18-41c