kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "105"
  name: redis-enterprise-scc
readOnlyRootFilesystem: false
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities:
  - SYS_RESOURCE
runAsUser:
  type: MustRunAs
  uid: 1001
fsGroup:
  type: MustRunAs
  uid: 1001
seLinuxContext:
  type: RunAsAny
