kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "110"
  name: redis-enterprise-operator
  namespace: supercloud
  labels:
    operators.coreos.com/redis-enterprise-operator-cert.supercloud: ''
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rec
  namespace: supercloud
  labels:
    operators.coreos.com/redis-enterprise-operator-cert.supercloud: ''