resources:
- operator/mongodb-sub.yaml
- operator/mongodb-og.yaml
# - operator/mongodb-catalog.yaml
- instance/mongodb-supercloud.yaml
- instance/mongodb-admin-user.yaml
- instance/mongodb-deployment.yaml
- instance/mongodb-opsmanger.yaml
- instance/ops-manager-config-secret.yaml
- instance/ops-manager-secrets.yaml