apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mongodb-deployment
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mongodb 
  template: 
    metadata: 
      labels: 
        app: mongodb
    spec: 
      terminationGracePeriodSeconds: 10 
      containers: 
        - name: mongo
          image: mongodb
          env: 
            - name: MONGODB_USERNAME 
              value: admin 
            - name: MONGODB_PASSWORD 
              value: password 
            - name: MONGODB_DBNAME 
              value: admin 
            - name: MONGODB_ROLE 
              value: root 
            - name: REPLICA_ID 
              value: mongoRS 
            - name: HOST 
              value: mongodb0 
          ports: 
            - containerPort: 27017 
          volumeMounts: 
            - name: mongo-key 
              mountPath: "/etc/secrets-volume" 
              readOnly: true 
            - name: mongo-persistent-storage 
              mountPath: /data 
      volumes: 
      - name: mongo-key 
        secret: 
          defaultMode: 0400 
          secretName: mongo-key 
      - name: mongo-persistent-storage 
        persistentVolumeClaim: 
          claimName: mongo-0-disk 
