apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
---
apiVersion: v1 
data: 
  mongodb-keyfile: cGFzc3dvcmQ=
kind: Secret 
metadata: 
  name: mongo-key 
  namespace: mongodb 
type: Opaque 