apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '205'
  name: ops-manager
  namespace: supercloud
spec:
  externalConnectivity:
    type: NodePort
  applicationDatabase:
    members: 3
    version: 5.0.14-ent
  configuration:
    mms.fromEmailAddr: admin@superclouddemo.com
  adminCredentials: ops-manager-admin-secret
  version: 6.0.3