apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '210'
  name: ops-manager-mongo-config
  namespace: supercloud
data:
  baseUrl: http://ops-manager-svc.supercloud.svc.cluster.local:8080